config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  mount Ckeditor::Engine => '/ckeditor'

  post 'newsletter/subscribe', to: 'newsletter#subscribe', defaults: { format: 'json' }

  # records
  scope module: 'records', as: 'records' do
    resources :posts, path: 'news', only: [:index, :show]
    resources :artists, only: [:index, :show]
    resources :releases, only: [:index, :show]
    resources :events, only: [:index]
    get 'about', to: 'statics#about'
    get 'press', to: 'statics#press'
  end

  # booking
  constraints subdomain: 'booking' do
    scope module: 'booking', as: 'booking' do
      root to: 'home#index', as: 'root'
      resources :artists, only: [:index, :show]
      resources :events, only: [:index]
    end
  end

  # www.moonleerecords.com
  root to: 'records/home#index'
end

app/controllers/records/artists_controller.rb
module Records
  class ArtistsController < Records::BaseController
    before_action do
      promoted_releases(3)
      upcoming_events(5)
      social_posts
    end

    def index
      @artists = Artist.on_records
      meta_tags('Artists', 'Label artists')
    end

    def show
      @artist = Artist.friendly.find(params[:id])
      @cover_image = {
        image: @artist.image,
        type: 'artist'
      }
      meta_tags(@artist.name, @artist.description, @artist.image.url(:large))
    end
  end
end

app/controllers/records/base_controller.rb
module Records
  class BaseController < ApplicationController
    layout 'records/layouts/application'

    def upcoming_events(limit = nil)
      @upcoming_events = Event.on_records.upcoming_per_date.limit(limit)
    end

    def promoted_releases(latest_count = 5)
      @upcoming_releases = Release.upcoming
      @latest_releases = (@upcoming_releases | Release.latest).take(latest_count)
    end

    def social_posts
      @social_posts = SocialPost.twitter.take(1) + SocialPost.instagram.take(2) + SocialPost.youtube.take(2)
    end

    def custom_header(title, text, image = nil)
      @custom_header = {
        title: title,
        text: text,
        image: image
      }
    end

    def meta_tags(title, description = '', image = nil)
      image = '/assets/missing.png' if image.nil?
      @meta_tags = {
        title: title == '' ? 'Moonlee Records' : "Moonlee Records - #{title}",
        description: description == '' ? 'Moonlee Records is an independent record label from Ljubljana, Slovenia. Established in 2004.' : description,
        image: "#{request.base_url}#{image}",
        url: request.original_url
      }
    end
  end
end

app/controllers/records/events_controller.rb
module Records
  class EventsController < Records::BaseController
    before_action do
      promoted_releases(3)
      upcoming_events(5)
      social_posts
    end

    def index
      @events = Event.on_records.upcoming_per_artist.group_by(&:artist)
      meta_tags('Shows', 'Upcoming shows from Moonlee artists')
    end
  end
end

app/controllers/records/home_controller.rb
module Records
  class HomeController < Records::BaseController
    before_action do
      promoted_releases(5)
      upcoming_events(5)
      social_posts
    end

    def index
      @news = Post.on_records.published.first(3)
      @slides = Slide.on_records.active
      meta_tags('', '')
    end
  end
end

app/controllers/records/posts_controller.rb
module Records
  class PostsController < Records::BaseController
    before_action do
      promoted_releases(3)
      upcoming_events(5)
      social_posts
    end

    def index
      @news = admin_user_signed_in? ? Post.on_records.page(params[:page]) : Post.on_records.published.page(params[:page])
      meta_tags('News', 'Latest news from Moonlee Records')
    end

    def show
      @post = Post.friendly.find(params[:id])
      @latest_news = Post.on_records.published.limit(5)
      @cover_image = {
        image: @post.image,
        type: 'post'
      }
      @cover_video = @post.youtube_iframe('100%', '100%') if @post.youtube_video
      meta_tags(@post.title, @post.body, @post.image.url(:large))
    end
  end
end

app/controllers/records/releases_controller.rb
module Records
  class ReleasesController < Records::BaseController
    before_action do
      promoted_releases(3)
      upcoming_events(5)
      social_posts
    end

    def index
      @releases = Release.internal_releases
      meta_tags('Releases', 'Releases from our artists')
    end

    def show
      @release = Release.friendly.find(params[:id])
      @cover_image = {
        image: @release.artists.first.image,
        type: 'release'
      }
      meta_tags("#{@release.artists_names} - #{@release.title}", @release.description, @release.cover.url(:large))
    end
  end
end

app/controllers/records/statics_controller.rb
module Records
  class StaticsController < Records::BaseController
    before_action do
      promoted_releases(3)
      upcoming_events(5)
      social_posts
    end

    def about
      custom_header(
        'About Us',
        '<strong>Moonlee Records</strong> is an independent record label established and run since 2004 by a ' \
'handful of music enthusiasts from Slovenia and Croatia under the command of <strong>Mr. Moonlee</strong>, a '\
'giant lemon not very fond of being squeezed. In 2011, Moonlee Records expanded into <strong>Moonlee Booking</strong> '\
'to organise shows and tours for Moonlee bands in Slovenia and abroad.',
        'about/moonlee-about.svg'
      )
      meta_tags('About', 'Get in touch with us!')
    end

    def press
      @artists = Artist.on_records.order(:name)
      meta_tags('Press Photos', "Moonlee's bands press photos.")
    end
  end
end

app/views/records/layouts/_footer.html.slim
footer.page-footer
  = render partial: 'records/shared/social',
           locals: { title: 'Social Media', social_posts: @social_posts }
  = render partial: 'records/shared/newsletter'
  = render partial: 'records/shared/footer_links'

app/views/records/layouts/_header.html.slim
header.page-header
  div.nav-container
    = link_to '', root_path, class: 'moonlee-logo moonlee-logo-header', title: 'Navigate to home page'
    input type='checkbox' id='navigation-trigger' class='navigation-trigger'
    label for='navigation-trigger' class='navigation-trigger-label'
    nav.navigation.site-navigation
      ul
        li
          = link_to 'Home', root_path
        = navigation_link('News', records_posts_path)
        = navigation_link('Releases', records_releases_path)
        = navigation_link('Artists', records_artists_path)
        = navigation_link('Shows', records_events_path)
        = navigation_link('About', records_about_path)
        li
          = link_to 'Store', '//store.moonleerecords.com/', target: '_blank'
    nav.navigation.section-navigation
      ul
        /li
        /  = link_to booking_root_path, target: '_blank' do
        /    i.fa.fa-custom-booking
        /    = 'Booking'
        li
          = link_to '//store.moonleerecords.com/', target: '_blank' do
            i.fa.fa-custom-store
            = 'Store'
  = render partial: 'records/shared/slider', locals: { slides: @slides }
  = render partial: 'records/shared/cover_header',
           locals: { cover_image: @cover_image, cover_video: @cover_video, artist: @artist, release: @release }
  = render partial: 'records/shared/custom_header',
           locals: { custom_header: @custom_header }

app/views/records/layouts/application.html.slim
doctype html
/[if lt IE 7]
html.no-js.ie6.oldie lang="en"
/[if IE 7]
html.no-js.ie7.oldie lang="en"
/[if IE 8]
html.no-js.ie8.oldie lang="en"
/[if gte IE 8]
html.no-js lang="en"
html
  head
    = render partial: 'records/shared/meta_tags'
    = content_for?(:meta_tags) ? yield(:meta_tags) : ''
    = stylesheet_link_tag 'records', media: 'all'
    = csrf_meta_tags
    link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png"
    link rel="icon" type="image/png" href="/favicon-32x32.png" sizes="32x32"
    link rel="icon" type="image/png" href="/favicon-16x16.png" sizes="16x16"
    link rel="manifest" href="/manifest.json"
    link rel="mask-icon" href="/safari-pinned-tab.svg" color="#253237"
    meta name="theme-color" content="#ffffff"
    meta name="viewport" content="width=device-width, height=device-height, initial-scale=1.0, user-scalable=0, minimum-scale=1.0, maximum-scale=1.0"
  body
    div id='fb-root'
    javascript:
      (function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.8&appId=211989012541313";
      fjs.parentNode.insertBefore(js, fjs);
      }(document, 'script', 'facebook-jssdk'));
    .container
      = render partial: 'records/layouts/header'
      div.content role='main'
        = yield
      = render partial: 'records/layouts/footer'
    = render 'cookies_eu/consent_banner'
    = javascript_include_tag 'records'

    - if Rails.env.production?
      javascript:
        (function (i, s, o, g, r, a, m) {
            i['GoogleAnalyticsObject'] = r;
            i[r] = i[r] || function () {
                    (i[r].q = i[r].q || []).push(arguments)
                }, i[r].l = 1 * new Date();
            a = s.createElement(o),
                m = s.getElementsByTagName(o)[0];
            a.async = 1;
            a.src = g;
            m.parentNode.insertBefore(a, m)
        })(window, document, 'script', 'https://www.google-analytics.com/analytics.js', 'ga');
        ga('create', "#{ENV['GOOGLE_ANALYTICS_TRACKING_ID']}", 'auto');
        ga('send', 'pageview');

/[if lt IE 7]
  script src="//ajax.googleapis.com/ajax/libs/chrome-frame/1.0.3/CFInstall.min.js"
  javascript:
    window.attachEvent("onload",function(){CFInstall.check({mode:"overlay"})})