config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  mount Ckeditor::Engine => '/ckeditor'

  post 'newsletter/subscribe', to: 'newsletter#subscribe', defaults: { format: 'json' }

  # records
  scope module: 'records', as: 'records' do
    resources :posts, path: 'news', only: [:index, :show]
    resources :artists, only: [:index, :show]
    resources :releases, only: [:index, :show]
    resources :events, only: [:index]
    get 'about', to: 'statics#about'
    get 'press', to: 'statics#press'
  end

  # booking
  constraints subdomain: 'booking' do
    scope module: 'booking', as: 'booking' do
      root to: 'home#index', as: 'root'
      resources :artists, only: [:index, :show]
      resources :events, only: [:index]
    end
  end

  # www.moonleerecords.com
  root to: 'records/home#index'
end

app/models/post.rb
class Post < ApplicationRecord
  VISIBILITY_OPTIONS = %w(public hidden).freeze
  AVAILABLE_CATEGORIES = %w(news).freeze

  extend FriendlyId
  include YoutubeVideo

  friendly_id :custom_slug, use: :slugged

  paginates_per 20

  default_scope { order('published_at DESC') }

  has_attached_file :image,
                    styles: {
                      large: '1250x1250>',
                      medium: '400x400#',
                      small: '100x100#'
                    }

  validates :title, presence: true
  validates :body, presence: true
  validates :published_at, presence: true
  validates :visibility, inclusion: { in: VISIBILITY_OPTIONS }
  validates :categories, length: { minimum: 1 }
  validate :validate_categories

  validates_attachment_content_type :image, content_type: %r{\Aimage\/.*\Z}

  scope :published, -> { where('published_at <= ?', Time.zone.now).where(visibility: 'public') }
  scope :on_records, -> { where(records: true) }
  scope :on_booking, -> { where(booking: true) }
  scope :hidden, -> { where(records: false, booking: false) }

  before_validation :assign_published_at
  before_save :assign_default_image

  def youtube_iframe(width = '560', height = '315')
    "<iframe width='#{width}' height='#{height}' src='https://www.youtube.com/embed/#{youtube_video_id(youtube_video)}?modestbranding=1&autohide=1&showinfo=0&controls=0' frameborder='0' allowfullscreen></iframe>" if youtube_video.present?
  end

  def body
    self[:body].gsub('&nbsp;', ' ') if self[:body].present?
  end

  def tags_raw
    tags.join(', ') unless tags.nil?
  end

  def tags_raw=(values)
    self.tags = values.split(',').map(&:strip)
  end

  def self.visibility_options
    VISIBILITY_OPTIONS
  end

  def self.available_categories
    AVAILABLE_CATEGORIES
  end

  private

  def custom_slug
    "#{published_at.strftime('%Y/%m/%d')} #{title}"
  end

  def assign_published_at
    self.published_at = created_at if published_at.nil?
  end

  def assign_default_image
    self.image = open("https://img.youtube.com/vi/#{youtube_video_id(youtube_video)}/0.jpg") if youtube_video.present?
  end

  def validate_categories
    categories = self.categories.reject!(&:empty?)
    invalid_categories = Array(categories) - AVAILABLE_CATEGORIES
    errors.add(:categories, 'Not all the categories are valid') if invalid_categories.count > 0
  end
end

app/controllers/records/artists_controller.rb
module Records
  class ArtistsController < Records::BaseController
    before_action do
      promoted_releases(3)
      upcoming_events(5)
      social_posts
    end

    def index
      @artists = Artist.on_records
      meta_tags('Artists', 'Label artists')
    end

    def show
      @artist = Artist.friendly.find(params[:id])
      @cover_image = {
        image: @artist.image,
        type: 'artist'
      }
      meta_tags(@artist.name, @artist.description, @artist.image.url(:large))
    end
  end
end

app/controllers/records/base_controller.rb
module Records
  class BaseController < ApplicationController
    layout 'records/layouts/application'

    def upcoming_events(limit = nil)
      @upcoming_events = Event.on_records.upcoming_per_date.limit(limit)
    end

    def promoted_releases(latest_count = 5)
      @upcoming_releases = Release.upcoming
      @latest_releases = (@upcoming_releases | Release.latest).take(latest_count)
    end

    def social_posts
      @social_posts = SocialPost.twitter.take(1) + SocialPost.instagram.take(2) + SocialPost.youtube.take(2)
    end

    def custom_header(title, text, image = nil)
      @custom_header = {
        title: title,
        text: text,
        image: image
      }
    end

    def meta_tags(title, description = '', image = nil)
      image = '/assets/missing.png' if image.nil?
      @meta_tags = {
        title: title == '' ? 'Moonlee Records' : "Moonlee Records - #{title}",
        description: description == '' ? 'Moonlee Records is an independent record label from Ljubljana, Slovenia. Established in 2004.' : description,
        image: "#{request.base_url}#{image}",
        url: request.original_url
      }
    end
  end
end

app/controllers/records/events_controller.rb
module Records
  class EventsController < Records::BaseController
    before_action do
      promoted_releases(3)
      upcoming_events(5)
      social_posts
    end

    def index
      @events = Event.on_records.upcoming_per_artist.group_by(&:artist)
      meta_tags('Shows', 'Upcoming shows from Moonlee artists')
    end
  end
end

app/controllers/records/home_controller.rb
module Records
  class HomeController < Records::BaseController
    before_action do
      promoted_releases(5)
      upcoming_events(5)
      social_posts
    end

    def index
      @news = Post.on_records.published.first(3)
      @slides = Slide.on_records.active
      meta_tags('', '')
    end
  end
end

app/controllers/records/posts_controller.rb
module Records
  class PostsController < Records::BaseController
    before_action do
      promoted_releases(3)
      upcoming_events(5)
      social_posts
    end

    def index
      @news = admin_user_signed_in? ? Post.on_records.page(params[:page]) : Post.on_records.published.page(params[:page])
      meta_tags('News', 'Latest news from Moonlee Records')
    end

    def show
      @post = Post.friendly.find(params[:id])
      @latest_news = Post.on_records.published.limit(5)
      @cover_image = {
        image: @post.image,
        type: 'post'
      }
      @cover_video = @post.youtube_iframe('100%', '100%') if @post.youtube_video
      meta_tags(@post.title, @post.body, @post.image.url(:large))
    end
  end
end

app/controllers/records/releases_controller.rb
module Records
  class ReleasesController < Records::BaseController
    before_action do
      promoted_releases(3)
      upcoming_events(5)
      social_posts
    end

    def index
      @releases = Release.internal_releases
      meta_tags('Releases', 'Releases from our artists')
    end

    def show
      @release = Release.friendly.find(params[:id])
      @cover_image = {
        image: @release.artists.first.image,
        type: 'release'
      }
      meta_tags("#{@release.artists_names} - #{@release.title}", @release.description, @release.cover.url(:large))
    end
  end
end

app/controllers/records/statics_controller.rb
module Records
  class StaticsController < Records::BaseController
    before_action do
      promoted_releases(3)
      upcoming_events(5)
      social_posts
    end

    def about
      custom_header(
        'About Us',
        '<strong>Moonlee Records</strong> is an independent record label established and run since 2004 by a ' \
'handful of music enthusiasts from Slovenia and Croatia under the command of <strong>Mr. Moonlee</strong>, a '\
'giant lemon not very fond of being squeezed. In 2011, Moonlee Records expanded into <strong>Moonlee Booking</strong> '\
'to organise shows and tours for Moonlee bands in Slovenia and abroad.',
        'about/moonlee-about.svg'
      )
      meta_tags('About', 'Get in touch with us!')
    end

    def press
      @artists = Artist.on_records.order(:name)
      meta_tags('Press Photos', "Moonlee's bands press photos.")
    end
  end
end

app/views/records/posts/index.html.slim
- unless @news.nil? || @news.empty?
  section.page-section.narrower.items-list.posts-list
    - @news.each_with_index do |post, index|
      article.post-item.items-list-group class=('painted' if index == 0)
        div.item-column.column-2-3
          = link_to records_post_path(post), title: post.title do
            h3.post-title
              = post.title
          time.post-date datetime=post.published_at
            = localize(post.published_at.to_date)
          div.text-block.post-body
            = raw(post.body)
        div.item-column.column-1-3
          = link_to records_post_path(post), title: post.title do
            div.post-image style="background-image: url(#{post.image.url(:medium)})"
              - if post.youtube_video.present?
                div.post-with-video
                  i.fa.fa-play-circle-o.fa-4x
    = paginate @news, left: 3, right: 3

app/views/records/posts/show.html.slim
section.page-section.narrower.post-show
  article.items-list.items-list-group
    div.post-main.item-column.column-6-9
      h2.post-title
        = @post.title
      time.post-date datetime=@post.published_at
        = localize(@post.published_at)
      hr.hr-style-1
      div.post-body.text-block
        = raw(@post.body)
    div.post-side.item-column.column-3-9
      = '<div class="fb-page" data-href="https://www.facebook.com/moonleerecords/" data-tabs="timeline" data-height="500" data-width="400" data-small-header="true" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true"><blockquote cite="https://www.facebook.com/moonleerecords/" class="fb-xfbml-parse-ignore"><a href="https://www.facebook.com/moonleerecords/"></a></blockquote></div>'.html_safe
      h4
        = 'Latest News'
      section.latest-news
        - @latest_news.each_with_index do |post, index|
          article
            = link_to records_post_path(post), title: post.title do
              h3
                = post.title
            time.post-date datetime = post.published_at
              = localize(post.published_at.to_date)
          - if index != @latest_news.count - 1
            hr.hr-style-1
        = link_to 'Read all news', records_posts_path, class: 'link-button more-posts'