config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  mount Ckeditor::Engine => '/ckeditor'

  post 'newsletter/subscribe', to: 'newsletter#subscribe', defaults: { format: 'json' }

  # records
  scope module: 'records', as: 'records' do
    resources :posts, path: 'news', only: [:index, :show]
    resources :artists, only: [:index, :show]
    resources :releases, only: [:index, :show]
    resources :events, only: [:index]
    get 'about', to: 'statics#about'
    get 'press', to: 'statics#press'
  end

  # booking
  constraints subdomain: 'booking' do
    scope module: 'booking', as: 'booking' do
      root to: 'home#index', as: 'root'
      resources :artists, only: [:index, :show]
      resources :events, only: [:index]
    end
  end

  # www.moonleerecords.com
  root to: 'records/home#index'
end

app/models/artist.rb
class Artist < ApplicationRecord
  extend FriendlyId

  friendly_id :name, use: :slugged

  default_scope { order('artists.active DESC, artists.name ASC') }

  has_many :artist_members, dependent: :destroy
  has_many :members, through: :artist_members
  has_many :external_links, as: :linkable, dependent: :destroy
  has_many :artist_releases
  has_many :releases, through: :artist_releases
  has_many :events

  has_attached_file :image,
                    styles: {
                      large: '1250x1250>',
                      large_medium: '700x700>',
                      medium: '450x450>',
                      small: '100x100>'
                    },
                    convert_options: {
                      # -strip -depth 8
                      all: ''
                    }

  # TODO: compressions
  # TODO: change image sizes?

  accepts_nested_attributes_for :artist_members, allow_destroy: true
  accepts_nested_attributes_for :external_links, allow_destroy: true

  validates :name, presence: true
  validates_attachment_content_type :image, content_type: %r{\Aimage\/.*\Z}

  scope :with_songkick_id, -> { where.not(songkick_id: nil) }
  scope :on_records, -> { where(records: true) }
  scope :on_booking, -> { where(booking: true) }
  scope :hidden, -> { where(records: false, booking: false) }
  scope :active, -> { where(active: true) }
  scope :inactive, -> { where(active: false) }

  def genre
    releases.each do |release|
      return release.genre unless release.split_release?
    end
    self[:genre]
  end
end

app/controllers/records/artists_controller.rb
module Records
  class ArtistsController < Records::BaseController
    before_action do
      promoted_releases(3)
      upcoming_events(5)
      social_posts
    end

    def index
      @artists = Artist.on_records
      meta_tags('Artists', 'Label artists')
    end

    def show
      @artist = Artist.friendly.find(params[:id])
      @cover_image = {
        image: @artist.image,
        type: 'artist'
      }
      meta_tags(@artist.name, @artist.description, @artist.image.url(:large))
    end
  end
end

app/controllers/records/base_controller.rb
module Records
  class BaseController < ApplicationController
    layout 'records/layouts/application'

    def upcoming_events(limit = nil)
      @upcoming_events = Event.on_records.upcoming_per_date.limit(limit)
    end

    def promoted_releases(latest_count = 5)
      @upcoming_releases = Release.upcoming
      @latest_releases = (@upcoming_releases | Release.latest).take(latest_count)
    end

    def social_posts
      @social_posts = SocialPost.twitter.take(1) + SocialPost.instagram.take(2) + SocialPost.youtube.take(2)
    end

    def custom_header(title, text, image = nil)
      @custom_header = {
        title: title,
        text: text,
        image: image
      }
    end

    def meta_tags(title, description = '', image = nil)
      image = '/assets/missing.png' if image.nil?
      @meta_tags = {
        title: title == '' ? 'Moonlee Records' : "Moonlee Records - #{title}",
        description: description == '' ? 'Moonlee Records is an independent record label from Ljubljana, Slovenia. Established in 2004.' : description,
        image: "#{request.base_url}#{image}",
        url: request.original_url
      }
    end
  end
end

app/controllers/records/events_controller.rb
module Records
  class EventsController < Records::BaseController
    before_action do
      promoted_releases(3)
      upcoming_events(5)
      social_posts
    end

    def index
      @events = Event.on_records.upcoming_per_artist.group_by(&:artist)
      meta_tags('Shows', 'Upcoming shows from Moonlee artists')
    end
  end
end

app/controllers/records/home_controller.rb
module Records
  class HomeController < Records::BaseController
    before_action do
      promoted_releases(5)
      upcoming_events(5)
      social_posts
    end

    def index
      @news = Post.on_records.published.first(3)
      @slides = Slide.on_records.active
      meta_tags('', '')
    end
  end
end

app/controllers/records/posts_controller.rb
module Records
  class PostsController < Records::BaseController
    before_action do
      promoted_releases(3)
      upcoming_events(5)
      social_posts
    end

    def index
      @news = admin_user_signed_in? ? Post.on_records.page(params[:page]) : Post.on_records.published.page(params[:page])
      meta_tags('News', 'Latest news from Moonlee Records')
    end

    def show
      @post = Post.friendly.find(params[:id])
      @latest_news = Post.on_records.published.limit(5)
      @cover_image = {
        image: @post.image,
        type: 'post'
      }
      @cover_video = @post.youtube_iframe('100%', '100%') if @post.youtube_video
      meta_tags(@post.title, @post.body, @post.image.url(:large))
    end
  end
end

app/controllers/records/releases_controller.rb
module Records
  class ReleasesController < Records::BaseController
    before_action do
      promoted_releases(3)
      upcoming_events(5)
      social_posts
    end

    def index
      @releases = Release.internal_releases
      meta_tags('Releases', 'Releases from our artists')
    end

    def show
      @release = Release.friendly.find(params[:id])
      @cover_image = {
        image: @release.artists.first.image,
        type: 'release'
      }
      meta_tags("#{@release.artists_names} - #{@release.title}", @release.description, @release.cover.url(:large))
    end
  end
end

app/controllers/records/statics_controller.rb
module Records
  class StaticsController < Records::BaseController
    before_action do
      promoted_releases(3)
      upcoming_events(5)
      social_posts
    end

    def about
      custom_header(
        'About Us',
        '<strong>Moonlee Records</strong> is an independent record label established and run since 2004 by a ' \
'handful of music enthusiasts from Slovenia and Croatia under the command of <strong>Mr. Moonlee</strong>, a '\
'giant lemon not very fond of being squeezed. In 2011, Moonlee Records expanded into <strong>Moonlee Booking</strong> '\
'to organise shows and tours for Moonlee bands in Slovenia and abroad.',
        'about/moonlee-about.svg'
      )
      meta_tags('About', 'Get in touch with us!')
    end

    def press
      @artists = Artist.on_records.order(:name)
      meta_tags('Press Photos', "Moonlee's bands press photos.")
    end
  end
end

app/helpers/artists_helper.rb
module ArtistsHelper
  def years_active(formed, disbanded)
    disbanded ? "#{formed} - #{disbanded}" : "#{formed} - present"
  end
end

app/views/records/artists/index.html.slim
- unless @artists.nil? || @artists.empty?
  section.page-section.items-list.artists-list
    - @artists.active.each do |artist|
      article.item-column.marginless.column-1-2
        = link_to records_artist_path(artist),
                  class: 'artist-box',
                  style: "background-image: url('#{artist.image.url(:large_medium)}');",
                  alt: artist.name,
                  title: artist.name do
          h2.artist-name
            = artist.name
          /h3.artist-quote
          /  = artist.quote
  section.page-section.items-list.artists-list-inactive
    div.section-heading
      h2.section-title
        = 'Inactive artists'
    - @artists.inactive.each do |artist|
      article.item-column.column-1-3
        = link_to '',
                  records_artist_path(artist),
                  class: 'artist-box',
                  style: "background-image: url('#{artist.image.url(:medium)}');",
                  alt: artist.name,
                  title: artist.name
        h3.artist-name
          = link_to artist.name, records_artist_path(artist), title: artist.name

app/views/records/artists/show.html.slim
section.page-section.narrower.artist-show
  article.items-list.items-list-group
    div.artist-main.item-column.column-6-9.text-block
      p = raw(@artist.description)
      - if @artist.events.count > 0
        hr.hr-style-1
        h4 Upcoming shows
        ul.artist-upcoming-shows
          - @artist.events.first(5).each do |event|
            li
              = "#{localize(event.start_date)} @ #{event.venue.name}, #{event.venue.city} (#{event.venue.country_code})"
      - if @artist.releases.count > 0
        hr.hr-style-1
        div.artist-releases.items-list.items-list-group
          - @artist.releases.each do |release|
            div.artist-release.hover-item.hover-item-border.item-column.column-1-3
              = link_to records_release_path(release), class: 'release-cover', title: "#{release.artists_names} - #{release.title}" do
                = image_tag release.cover.url(:medium), alt: "#{release.artists_names} - #{release.title}"
              div.release-info
                span.release-number = release.catalog_number
                h3.release-title = release.title
    div.artist-side.item-column.column-3-9.text-block
      h4 Origin
      span = @artist.origin
      - if @artist.genre
        h4 Genre
        span = @artist.genre
      h4 Years active
      span = years_active(@artist.formed, @artist.disbanded)
      - if @artist.members.count > 0
        hr.hr-style-1
        h4 Members
        ul
          - @artist.artist_members.each do |member|
            li = member.role ? "#{member.name} - #{member.role}" : member.name
      - if @artist.external_links.count > 0
        hr.hr-style-1
        h4 Links
        ul
          - @artist.external_links.each do |link|
            li = link_to t(link.url_type), link.url, target: '_blank'